force-app/main/default/objects/Method__c/Method__c.object-meta.xml
<CustomObject>
    <label>Method</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Method__c/fields/V2MOM__c.field-meta.xml
<CustomField>
    <fullName>V2MOM__c</fullName>
    <label>V2MOM</label>
    <referenceTo>V2MOM__c</referenceTo>
    <relationshipLabel>Methods</relationshipLabel>
    <relationshipName>Methods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Obstacle__c/Obstacle__c.object-meta.xml
<CustomObject>
    <label>Obstacle</label>
    <nameField>
        <label>Obstacle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Obstacles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Obstacle__c/fields/V2MOM__c.field-meta.xml
<CustomField>
    <fullName>V2MOM__c</fullName>
    <label>V2MOM</label>
    <referenceTo>V2MOM__c</referenceTo>
    <relationshipLabel>Obstacles</relationshipLabel>
    <relationshipName>Obstacles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/V2MOM__c/V2MOM__c.object-meta.xml
<CustomObject>
    <label>V2MOM</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>V2MOM</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/V2MOM_SharePDFCtrlTest.cls
@isTest
public class V2MOM_SharePDFCtrlTest { 
    @isTest static void fetchObstaclesTest(){
        V2MOM__c v2momRecord = V2MOMQ_TestUtil.createV2MOM();
        Obstacle__c obs_1 = V2MOMQ_TestUtil.createObstacle(v2momRecord.Id);
        Obstacle__c obs_2 = V2MOMQ_TestUtil.createObstacle(v2momRecord.Id);
        
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(v2momRecord);
        V2MOM_SharePDFCtrl obj = new V2MOM_SharePDFCtrl(sc);
        obj.v2momObj = v2momRecord;
        List<Obstacle__c> obstacles = obj.fetchObstacles();
        Test.stopTest();
    }
	@isTest static void fetchMethodsTest(){
        V2MOM__c v2momRecord = V2MOMQ_TestUtil.createV2MOM();
        Method__c method_1 = V2MOMQ_TestUtil.createMethod(v2momRecord.Id);
        Method__c method_2 = V2MOMQ_TestUtil.createMethod(v2momRecord.Id);
        
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(v2momRecord);
        V2MOM_SharePDFCtrl obj = new V2MOM_SharePDFCtrl(sc);
        obj.v2momObj = v2momRecord;
        List<Method__c> obstacles = obj.fetchMethods();
        Test.stopTest();
    }
}