force-app/main/default/objects/Measure__c/Measure__c.object-meta.xml
<CustomObject>
    <label>Measure</label>
    <nameField>
        <label>Measure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Measures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Measure__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <referenceTo>Method__c</referenceTo>
    <relationshipLabel>Measures</relationshipLabel>
    <relationshipName>Measures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Q1__c.field-meta.xml
<CustomField>
    <fullName>Q1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Q1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Q1_Progress__c.field-meta.xml
<CustomField>
    <fullName>Q1_Progress__c</fullName>
    <formula>IF(Is_Assigned_Measure__c, Q1_Team_Value__c/Q1_Team_Target__c,
(CASE(Q1_Type__c,  'Completion', IF(OR( ISNULL(Q1_Target__c) ,Q1_Target__c == 0) , 0, Q1_Value__c/Q1_Target__c)  ,
 'Progress', (CASE(Q1_Status__c, 'Not Started', 0, 'Canceled', 0 , 'Behind Schedule', 0.25,'On Track', 0.50,'Completed', 1,0)),0) ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Q1 Progress</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Q1_Status__c.field-meta.xml
<CustomField>
    <fullName>Q1_Status__c</fullName>
    <label>Q1 Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Behind Schedule</fullName>
            </value>
            <value>
                <fullName>On Track</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Q1_Type__c.field-meta.xml
<CustomField>
    <fullName>Q1_Type__c</fullName>
    <label>Q1 Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Progress</fullName>
            </value>
            <value>
                <fullName>Completion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Q2__c.field-meta.xml
<CustomField>
    <fullName>Q2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Q2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Q2_Progress__c.field-meta.xml
<CustomField>
    <fullName>Q2_Progress__c</fullName>
    <formula>IF(Is_Assigned_Measure__c, Q2_Team_Value__c/Q2_Team_Target__c,
(CASE(TEXT(Q2_Type__c),&apos;Completion&apos;,  IF(OR( ISNULL(Q2_Target__c) ,Q2_Target__c == 0) , 0, Q2_Value__c/Q2_Target__c) ,
&apos;Progress&apos;,(CASE(TEXT(Q2_Status__c), &apos;Not Started&apos;, 0, &apos;Canceled&apos;, 0 ,&apos;Behind Schedule&apos;, 0.25 ,&apos;On Track&apos;, 0.50 ,&apos;Completed&apos;, 1,0)),0)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Q2 Progress</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Q2_Status__c.field-meta.xml
<CustomField>
    <fullName>Q2_Status__c</fullName>
    <label>Q2 Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Behind Schedule</fullName>
            </value>
            <value>
                <fullName>On Track</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Q2_Type__c.field-meta.xml
<CustomField>
    <fullName>Q2_Type__c</fullName>
    <label>Q2 Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Progress</fullName>
            </value>
            <value>
                <fullName>Completion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Q3__c.field-meta.xml
<CustomField>
    <fullName>Q3__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Q3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Q3_Progress__c.field-meta.xml
<CustomField>
    <fullName>Q3_Progress__c</fullName>
    <formula>IF(Is_Assigned_Measure__c, Q3_Team_Value__c/Q3_Team_Target__c,
(CASE(TEXT(Q3_Type__c),'Completion', IF(OR( ISNULL(Q3_Target__c) ,Q3_Target__c == 0) , 0, Q3_Value__c/Q3_Target__c)  ,
'Progress',(CASE(TEXT(Q3_Status__c), 'Not Started', 0, 'Canceled', 0 ,'Behind Schedule', 0.25 ,'On Track', 0.50 ,'Completed', 1,0)),0)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Q3 Progress</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Q3_Status__c.field-meta.xml
<CustomField>
    <fullName>Q3_Status__c</fullName>
    <label>Q3 Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Behind Schedule</fullName>
            </value>
            <value>
                <fullName>On Track</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Q3_Type__c.field-meta.xml
<CustomField>
    <fullName>Q3_Type__c</fullName>
    <label>Q3 Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Progress</fullName>
            </value>
            <value>
                <fullName>Completion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Q4__c.field-meta.xml
<CustomField>
    <fullName>Q4__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Q4</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Q4_Progress__c.field-meta.xml
<CustomField>
    <fullName>Q4_Progress__c</fullName>
    <formula>IF(Is_Assigned_Measure__c, Q4_Team_Value__c/Q4_Team_Target__c,
(CASE(TEXT(Q4_Type__c),&apos;Completion&apos;,  IF(OR( ISNULL(Q4_Target__c) ,Q4_Target__c == 0) , 0, Q4_Value__c/Q4_Target__c) ,
&apos;Progress&apos;,(CASE(TEXT(Q4_Status__c), &apos;Not Started&apos;, 0, &apos;Canceled&apos;, 0 ,&apos;Behind Schedule&apos;, 0.25 ,&apos;On Track&apos;, 0.50 ,&apos;Completed&apos;, 1,0)),0)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Q4 Progress</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Q4_Type__c.field-meta.xml
<CustomField>
    <fullName>Q4_Type__c</fullName>
    <label>Q4 Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Progress</fullName>
            </value>
            <value>
                <fullName>Completion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Method__c/Method__c.object-meta.xml
<CustomObject>
    <label>Method</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Method__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Method__c/fields/Q1__c.field-meta.xml
<CustomField>
    <fullName>Q1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Q1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Method__c/fields/Q1_Progress__c.field-meta.xml
<CustomField>
    <fullName>Q1_Progress__c</fullName>
    <formula>Q1_Total__c /  Q1_Count__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Q1 Progress</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Method__c/fields/Q2__c.field-meta.xml
<CustomField>
    <fullName>Q2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Q2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Method__c/fields/Q2_Progress__c.field-meta.xml
<CustomField>
    <fullName>Q2_Progress__c</fullName>
    <formula>Q2_Total__c /  Q2_Count__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Q2 Progress</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Method__c/fields/Q3__c.field-meta.xml
<CustomField>
    <fullName>Q3__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Q3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Method__c/fields/Q3_Progress__c.field-meta.xml
<CustomField>
    <fullName>Q3_Progress__c</fullName>
    <formula>Q3_Total__c /  Q3_Count__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Q3 Progress</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Method__c/fields/Q4__c.field-meta.xml
<CustomField>
    <fullName>Q4__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Q4</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Method__c/fields/Q4_Progress__c.field-meta.xml
<CustomField>
    <fullName>Q4_Progress__c</fullName>
    <formula>Q4_Total__c /  Q4_Count__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Q4 Progress</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Method__c/fields/V2MOM__c.field-meta.xml
<CustomField>
    <fullName>V2MOM__c</fullName>
    <label>V2MOM</label>
    <referenceTo>V2MOM__c</referenceTo>
    <relationshipLabel>Methods</relationshipLabel>
    <relationshipName>Methods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Obstacle__c/Obstacle__c.object-meta.xml
<CustomObject>
    <label>Obstacle</label>
    <nameField>
        <label>Obstacle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Obstacles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Obstacle__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Obstacle__c/fields/V2MOM__c.field-meta.xml
<CustomField>
    <fullName>V2MOM__c</fullName>
    <label>V2MOM</label>
    <referenceTo>V2MOM__c</referenceTo>
    <relationshipLabel>Obstacles</relationshipLabel>
    <relationshipName>Obstacles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/V2MOM__c/V2MOM__c.object-meta.xml
<CustomObject>
    <label>V2MOM</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>V2MOM</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/V2MOM__c/fields/Q1_Progress__c.field-meta.xml
<CustomField>
    <fullName>Q1_Progress__c</fullName>
    <formula>Q1_Total__c / Q1_Count__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Q1 Progress</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/V2MOM__c/fields/Q2_Progress__c.field-meta.xml
<CustomField>
    <fullName>Q2_Progress__c</fullName>
    <formula>Q2_Total__c / Q2_Count__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Q2 Progress</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/V2MOM__c/fields/Q3_Progress__c.field-meta.xml
<CustomField>
    <fullName>Q3_Progress__c</fullName>
    <formula>Q3_Total__c / Q3_Count__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Q3 Progress</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/V2MOM__c/fields/Q4_Progress__c.field-meta.xml
<CustomField>
    <fullName>Q4_Progress__c</fullName>
    <formula>Q4_Total__c / Q4_Count__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Q4 Progress</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/V2MOM_SharePDFCtrl.cls
public class V2MOM_SharePDFCtrl {
    
    public V2MOM__c v2momObj;
    public List<Method__c> methodsList {get; set;}
    public List<Obstacle__c> obsList {get; set;}
    
    public V2MOM_SharePDFCtrl(ApexPages.StandardController stdController) {
        this.v2momObj = (V2MOM__c)stdController.getRecord();
        methodsList = new List<Method__c>();
        obsList = new List<Obstacle__c>();
        fetchMethods();
        fetchObstacles();
    }
    
    public List<Method__c> fetchMethods() {
        
        methodsList = [select id, Name, Description__c,
                                      (select id, Name, Description__c, Comments__c, 
                                       Q1__c, Q1_Progress__c,
                                       Q2__c, Q2_Progress__c,
                                       Q3__c, Q3_Progress__c,
                                       Q4__c, Q4_Progress__c,
                                       Q1_Type__c, Q1_Status__c,
                                       Q2_Type__c, Q2_Status__c,
                                       Q3_Type__c, Q3_Status__c,
                                       Q4_Type__c, Q4_Status__c
                                       from Measures__r) 
                                      from Method__c where V2MOM__c =: v2momObj.Id WITH SECURITY_ENFORCED];

		return methodsList;
    }
    
    public List<Obstacle__c> fetchObstacles(){
        obsList = [select id, Name, Description__c from Obstacle__c where V2MOM__c =: v2momObj.Id WITH SECURITY_ENFORCED];
        return obsList;
    }
    
}