force-app/main/default/objects/Measure__c/Measure__c.object-meta.xml
<CustomObject>
    <label>Measure</label>
    <nameField>
        <label>Measure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Measures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Measure__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <referenceTo>Method__c</referenceTo>
    <relationshipLabel>Measures</relationshipLabel>
    <relationshipName>Measures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Obstacles__c.field-meta.xml
<CustomField>
    <fullName>Obstacles__c</fullName>
    <label>Obstacles</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Q1__c.field-meta.xml
<CustomField>
    <fullName>Q1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Q1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Q1_Target__c.field-meta.xml
<CustomField>
    <fullName>Q1_Target__c</fullName>
    <label>Q1 Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Q1_Value__c.field-meta.xml
<CustomField>
    <fullName>Q1_Value__c</fullName>
    <label>Q1 Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Q2__c.field-meta.xml
<CustomField>
    <fullName>Q2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Q2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Q2_Target__c.field-meta.xml
<CustomField>
    <fullName>Q2_Target__c</fullName>
    <label>Q2 Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Q2_Value__c.field-meta.xml
<CustomField>
    <fullName>Q2_Value__c</fullName>
    <label>Q2 Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Measure_Team_Member__c/Measure_Team_Member__c.object-meta.xml
<CustomObject>
    <label>Measure Team Member</label>
    <nameField>
        <displayFormat>MTM-{000000}</displayFormat>
        <label>Team Member Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Measure Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Measure_Team_Member__c/fields/Measure__c.field-meta.xml
<CustomField>
    <fullName>Measure__c</fullName>
    <label>Measure</label>
    <referenceTo>Measure__c</referenceTo>
    <relationshipLabel>Measure Team Members</relationshipLabel>
    <relationshipName>Measure_Team_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Measure_Team_Member__c/fields/Q1__c.field-meta.xml
<CustomField>
    <fullName>Q1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Q1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Measure_Team_Member__c/fields/Q1_Target__c.field-meta.xml
<CustomField>
    <fullName>Q1_Target__c</fullName>
    <label>Q1 Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Measure_Team_Member__c/fields/Q1_Value__c.field-meta.xml
<CustomField>
    <fullName>Q1_Value__c</fullName>
    <label>Q1 Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Measure_Team_Member__c/fields/Q2__c.field-meta.xml
<CustomField>
    <fullName>Q2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Q2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Measure_Team_Member__c/fields/Q2_Target__c.field-meta.xml
<CustomField>
    <fullName>Q2_Target__c</fullName>
    <label>Q2 Target</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Measure_Team_Member__c/fields/Q2_Value__c.field-meta.xml
<CustomField>
    <fullName>Q2_Value__c</fullName>
    <label>Q2 Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Method__c/Method__c.object-meta.xml
<CustomObject>
    <label>Method</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Method__c/fields/Q1__c.field-meta.xml
<CustomField>
    <fullName>Q1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Q1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Method__c/fields/Q2__c.field-meta.xml
<CustomField>
    <fullName>Q2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Q2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Method__c/fields/V2MOM__c.field-meta.xml
<CustomField>
    <fullName>V2MOM__c</fullName>
    <label>V2MOM</label>
    <referenceTo>V2MOM__c</referenceTo>
    <relationshipLabel>Methods</relationshipLabel>
    <relationshipName>Methods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/V2MOM__c/V2MOM__c.object-meta.xml
<CustomObject>
    <label>V2MOM</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>V2MOM</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/AssignMeasureTest.cls
@isTest
public class AssignMeasureTest {
    @isTest static void getMeasureAssigneesTestMethod(){
        V2MOM__c myv2mom = V2MOMQ_TestUtil.createV2MOM();
        Method__c method = V2MOMQ_TestUtil.createMethod(myv2mom.Id);
        Measure__c measure = V2MOMQ_TestUtil.createMeasure(method.Id);
        Measure_Team_Member__c teamMember = new Measure_Team_Member__c();
        String quarter = 'Q2';
        teamMember.Measure__c = measure.Id;
        teamMember.Q2__c = true;
        teamMember.Q2_Target__c  = 100;
        teamMember.Q2_Value__c  = 40;
        INSERT teamMember;
        
        Test.startTest();
        List<Measure_Team_Member__c> teamMembersList = AssignMeasure.getMeasureAssignees(measure.Id,quarter);
        //List<Measure_Team_Member__c> teamMembersList_1 = AssignMeasure.getMeasureAssignees(measure.Id,'Q5');
        Test.stopTest();
        System.assertEquals(1,teamMembersList.size());
        System.assertEquals(true,teamMembersList[0].Q2__c);
    }
    
    @isTest static void getMeasureTeamMemberRecordTestMethod(){
        V2MOM__c myv2mom = V2MOMQ_TestUtil.createV2MOM();
        Method__c method = V2MOMQ_TestUtil.createMethod(myv2mom.Id);
        Measure__c measure = V2MOMQ_TestUtil.createMeasure(method.Id);      
        
        Measure_Team_Member__c teamMember = new Measure_Team_Member__c();
        String quarter = 'Q2';
        teamMember.Measure__c = measure.Id;
        teamMember.Q2__c = true;
        teamMember.Q2_Target__c  = 100;
        teamMember.Q2_Value__c  = 40;
        INSERT teamMember;
        
        Measure_Team_Member__c teamMember_1 = new Measure_Team_Member__c();
        String quarter_1 = 'Q1';
        teamMember_1.Q1__c = true;
        teamMember_1.Measure__c = measure.Id;
        //teamMember_1.Q2__c = true;
        teamMember_1.Q1_Target__c  = 100;
        teamMember_1.Q1_Value__c  = 40;
        INSERT teamMember_1;
        
        Test.startTest();
        Measure_Team_Member__c teamMemberObj = AssignMeasure.getMeasureTeamMemberRecord(teamMember_1.Id);
        Test.stopTest();
        System.assertEquals(true,teamMemberObj.Q1__c);
        System.assertEquals(false,teamMemberObj.Q2__c);
    }
    
    @isTest static void getMeasureDetailsTestMethod(){
        V2MOM__c myv2mom = V2MOMQ_TestUtil.createV2MOM();
        Method__c method = V2MOMQ_TestUtil.createMethod(myv2mom.Id);
        Measure__c measure = V2MOMQ_TestUtil.createMeasure(method.Id);
        
        Measure_Team_Member__c teamMember = new Measure_Team_Member__c();
        String quarter = 'Q2';
        teamMember.Measure__c = measure.Id;
        teamMember.Q2__c = true;
        teamMember.Q2_Target__c  = 100;
        teamMember.Q2_Value__c  = 40;
        INSERT teamMember;
        
        Measure_Team_Member__c teamMember_1 = new Measure_Team_Member__c();
        String quarter_1 = 'Q1';
        teamMember_1.Q1__c = true;
        teamMember_1.Measure__c = measure.Id;
        //teamMember_1.Q2__c = true;
        teamMember_1.Q1_Target__c  = 100;
        teamMember_1.Q1_Value__c  = 40;
        INSERT teamMember_1;
        
        Test.startTest();
        Measure__c measure_1 = AssignMeasure.getMeasureDetails(measure.Id,'Q2');
        Test.stopTest();
        System.assertEquals('Obsctacles',measure_1.Obstacles__c);
        System.assertEquals(method.Id,measure_1.Method__c);
    }
}