force-app/main/default/objects/Measure__c/Measure__c.object-meta.xml
<CustomObject>
    <label>Measure</label>
    <nameField>
        <label>Measure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Measures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Measure__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <referenceTo>Method__c</referenceTo>
    <relationshipLabel>Measures</relationshipLabel>
    <relationshipName>Measures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Method__c/Method__c.object-meta.xml
<CustomObject>
    <label>Method</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Method__c/fields/V2MOM__c.field-meta.xml
<CustomField>
    <fullName>V2MOM__c</fullName>
    <label>V2MOM</label>
    <referenceTo>V2MOM__c</referenceTo>
    <relationshipLabel>Methods</relationshipLabel>
    <relationshipName>Methods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/V2MOM__c/V2MOM__c.object-meta.xml
<CustomObject>
    <label>V2MOM</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>V2MOM</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/V2MOM__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/V2MOM_LinkReportClassTest.cls
@isTest(SeeAllData=false)
public class V2MOM_LinkReportClassTest {
    @isTest static void fetchRecordsTestMethod(){
        V2MOM__c myv2mom = V2MOMQ_TestUtil.createV2MOM();
        Method__c method = V2MOMQ_TestUtil.createMethod(myv2mom.Id);
        Measure__c measure = V2MOMQ_TestUtil.createMeasure(method.Id);
        
        Test.startTest();
        List<V2MOM_LinkReportClass.RecordsData> records = V2MOM_LinkReportClass.fetchRecords('V2MOM__c', 'Status__c', '',myv2mom.Id);
        List<V2MOM_LinkReportClass.RecordsData> records_1 = V2MOM_LinkReportClass.fetchRecords('V2MOM__c', 'Name', 'V2MOM','');
        Test.stopTest();
        
        System.assertEquals(1, records.size());
        System.assertEquals(1, records_1.size());
    }
    
    @isTest(SeeAllData=true) static void getReportListTestMethod(){
        Test.startTest();
        List<Report> reports = V2MOM_LinkReportClass.getReportList();
        Test.stopTest();
        System.assertEquals(1, reports.size());
    }
    @isTest static void getReportListNullTestMethod(){
        Test.startTest();
        List<Report> reports = V2MOM_LinkReportClass.getReportList();
        Test.stopTest();
        System.assertEquals(null, reports);
    }
    
    @isTest(SeeAllData=true) static void getAggregateFieldsTestMethod(){
        Id rId;
        List<Report> reportsList = [select id from Report where Name='Sample Flow Report: Screen Flows'];
        if(reportsList != null && reportsList.size() > 0){
            rId = reportsList[0].Id;
        }
        Test.startTest();
        
		List<V2MOM_LinkReportClass.RecordsData> records = V2MOM_LinkReportClass.getAggregateFields(rId);
        List<V2MOM_LinkReportClass.RecordsData> records_1 = V2MOM_LinkReportClass.getAggregateFields(rId);
        Test.stopTest();
        System.assertEquals(records[records.size()-1].label, 'Record Count');
    }
    
    
    @isTest(SeeAllData = true) static void getAggregatesTestMethod(){
        
        Test.startTest();
        String reportId;
        List<Report> reportsList = [select id from Report where Name='Sample Flow Report: Screen Flows'];
        if(reportsList != null && reportsList.size() > 0){
            reportId = reportsList[0].Id;
        }
        
        List<String> aggs = V2MOM_LinkReportClass.getAggregates(reportId);
        V2MOM_LinkReportClass.getAggregateValue(reportId,aggs[0]);

        Test.stopTest();
        system.debug('r1'+aggs[0]);
        System.assertEquals(aggs[aggs.size()-1], 'Record Count');
    }
    
    @isTest(SeeAllData = true) static void getAggregateValueNegativeTestMethod(){
        
        String reportId;
        Test.startTest();
        List<Report> reportsList = [select id from Report where Name='Sample Flow Report: Screen Flows'];
        if(reportsList != null && reportsList.size() > 0){
            reportId = reportsList[0].Id;
        }
        
        List<String> aggs = V2MOM_LinkReportClass.getAggregates(reportId);
        V2MOM_LinkReportClass.getAggregateValue(reportId,'');
        
        Test.stopTest();


    }
}