force-app/main/default/objects/Measure__c/Measure__c.object-meta.xml
<CustomObject>
    <label>Measure</label>
    <nameField>
        <label>Measure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Measures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Measure__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <referenceTo>Method__c</referenceTo>
    <relationshipLabel>Measures</relationshipLabel>
    <relationshipName>Measures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Obstacles__c.field-meta.xml
<CustomField>
    <fullName>Obstacles__c</fullName>
    <label>Obstacles</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Q1__c.field-meta.xml
<CustomField>
    <fullName>Q1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Q1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Q2__c.field-meta.xml
<CustomField>
    <fullName>Q2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Q2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Q3__c.field-meta.xml
<CustomField>
    <fullName>Q3__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Q3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Measure__c/fields/Q4__c.field-meta.xml
<CustomField>
    <fullName>Q4__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Q4</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Measure_Team_Member__c/Measure_Team_Member__c.object-meta.xml
<CustomObject>
    <label>Measure Team Member</label>
    <nameField>
        <displayFormat>MTM-{000000}</displayFormat>
        <label>Team Member Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Measure Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Measure_Team_Member__c/fields/Measure__c.field-meta.xml
<CustomField>
    <fullName>Measure__c</fullName>
    <label>Measure</label>
    <referenceTo>Measure__c</referenceTo>
    <relationshipLabel>Measure Team Members</relationshipLabel>
    <relationshipName>Measure_Team_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Measure_Team_Member__c/fields/Q1__c.field-meta.xml
<CustomField>
    <fullName>Q1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Q1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Measure_Team_Member__c/fields/Q2__c.field-meta.xml
<CustomField>
    <fullName>Q2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Q2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Measure_Team_Member__c/fields/Q3__c.field-meta.xml
<CustomField>
    <fullName>Q3__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Q3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Measure_Team_Member__c/fields/Q4__c.field-meta.xml
<CustomField>
    <fullName>Q4__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Q4</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Measure_Team_Member__c/fields/Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Measure_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Method__c/Method__c.object-meta.xml
<CustomObject>
    <label>Method</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Method__c/fields/Q1__c.field-meta.xml
<CustomField>
    <fullName>Q1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Q1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Method__c/fields/Q2__c.field-meta.xml
<CustomField>
    <fullName>Q2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Q2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Method__c/fields/Q3__c.field-meta.xml
<CustomField>
    <fullName>Q3__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Q3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Method__c/fields/Q4__c.field-meta.xml
<CustomField>
    <fullName>Q4__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Q4</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AssignMeasure.cls
public with sharing class AssignMeasure {
    
    // This method helps in fetching measure team records of a measure. 
    @AuraEnabled(cacheable=true)
    public static List<Measure_Team_Member__c> getMeasureAssignees(Id MeasureId,String quarter){

        try{
            String quarterField = ''+quarter+'_Target__c';
            String quarterValue = ''+quarter + '_Value__c';
            String quarterName = ''+quarter+'__c';
            String progressField = ''+quarter+'_Progress__c';
            String measureValue = '\''+MeasureId+'\'';
            
            String query = 'Select Id, '+quarterName+', '+quarterField+', '+quarterValue+', '+progressField+', Team_Member__r.Name, Team_Member__r.Id FROM Measure_Team_Member__c where Measure__c = '+measureValue+' WITH SECURITY_ENFORCED';
            
            return Database.query(query);
        }catch(exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
    
     @AuraEnabled(cacheable=true)
    public static Measure_Team_Member__c getMeasureTeamMemberRecord(Id teamMemberId){
        return [SELECT Q1__c,Q2__c,Q3__c,Q4__c FROM Measure_Team_Member__c where Id = :teamMemberId WITH SECURITY_ENFORCED];
    }

    
    @AuraEnabled(cacheable=true)
    public static Measure__c getMeasureDetails(Id measureId,String quarter){
        String quarterPriority = ''+quarter+'_Priority__c';
        String measureIdString = '\''+measureId+'\'';
        String query = 'SELECT Id,Obstacles__c,Method__c,'+quarterPriority+' FROM Measure__c WHERE Id ='+measureIdString+' WITH SECURITY_ENFORCED' ;
        
        return Database.query(query);
    }
}